### ISSUE TITLE
question(js2coffee): nothing occurs

### ISSUE THREAD

**Issue by Kristinita** [nickdowse/RailsMagicClipboard#9]
### 1. Summary

If I paste JavaScript code to `.coffee` file via Rails Magic Clipboard, nothing occurs.

### 2. Environment

+ Windows 10 Enterprise LTSB 64-bit EN,
+ Sublime Text Build 3143,
+ js2coffee 2.2.0,
+ Rails Magic Clipboard 0.1.2.

### 3. Configuration

I have blank file `SashaRails.coffee`.

Part of my `User/Default (Windows).sublime-keymap` file:

```json
{
    "keys": ["ctrl+super+v"],
    "command": "rails_magic_clipboard"
},
```

### 4. Steps to reproduce

I reproduce the problem in a version of Sublime Text without plugins and user settings.

I copy JavaScript text from [**external resource**](https://www.npmjs.com/package/grunt-hello-world#overview):

```javascript
hello_world: {
     world: {
        name: "world"
     },
     other: {
        name: "name"
     }
  },
```

I open `SashaRails.coffee` → I press <kbd>Ctrl+Super+V</kbd>.

```python
key evt: control+super+v
command: rails_magic_clipboard {}
```

### 5. Expected behavior

```coffee
hello_world:
     world:
        name: "world"
     other:
        name: "name"
```

### 6. Actual behavior

Paste same code:

```javascript
hello_world: {
     world: {
        name: "world"
     },
     other: {
        name: "name"
     }
  },
```

Thanks.

**Comment by nickdowse** [comment]
Hi Kristinita, thanks for this report.

I see you're using Microsoft Windows, unfortunately the package doesn't support the Windows OS, as I'm not 100% sure how to get all the supporting packages on there. If you have any nice suggestions I'm happy to hear them :)

As for now, I'm going to close this as adding windows support isn't really something I'm going to do. If others want windows support throw a 👍 on the issue and if it gets popular enough I'll look into it :)
